### ISSUE TITLE
Media always defaulting to "Pushover"

### ISSUE THREAD

**Issue by OlivierdcMV** [zabbix-tooling/zabbix-ldap-sync#19] opened 2020-04-01 07:40 UTC
While implementing this script we noticed that the media type of the user was always defaulting to "Pushover". This happend in the get_media_typeid function. When we do the call, we can see in the description of the json output that the value is set to "Email" for media Email. When changing the filter to 'Name' in the function it seems to work.

Also, wildcard for OpenLDAP not working.

Zabbix version 4.4.6

**Comment by scoopex** [comment] 2020-04-03 12:03
I am sorry @OlivierdcMV it is difficult to understand what the problem is :-) What do you mean using the term "pushover"? Probably you can provide more details (an redacted configuration, example ldap results, debug output).

If you have some python knowhow, probably you can solve the problem by yourself. New contributors are very welcome :-) You can fork the repository and submit a pull request.

**Comment by OlivierdcMV** [comment] 2020-04-03 12:43
@scoopex  when we set the value of Name in the config to email, it does not alter the value for email as the media of the user, but for the media type "pushover"

**Comment by blodone** [comment] 2020-08-28 09:27
@OlivierdcMV i also don't understand what you mean by "setting the value of Name in the config to email". please give a example. As it is mentioned, wildcard search is only tested with active directory

**Comment by scoopex** [comment] 2021-02-25 00:09
There was a bug in media selection. This is fixed now.
I see no reason the wildcard searching does not work with openldap. Please reopen with a concrete example and a example data structure.

**Closed as completed by scoopex** 2021-02-25 00:09 UTC
