### ISSUE TITLE
Error on the 1st login

### ISSUE THREAD

**Issue by svgaikwad** [zabbix-tooling/zabbix-ldap-sync#28] opened 2021-04-06 10:45 UTC
Hi Team,
              I am facing a issue when i try to create/add a new user using the tool.
              dashboard appears in a weird way i have updated the screen short on the same.
              zabbix version which i am using is 4.0.6. Please help me with issue.

![weird_dashboard_2](https://user-images.githubusercontent.com/27721836/113700966-219ca500-96f5-11eb-8974-2755aea3a4db.PNG)

user config as per below. 
```
[user]
# use "type" for releases prior 5.2
type = 1
# use "roleid" for releases after 5.2
#roleid = 1
#timezone = Europe/Berlin
#rows_per_page = 100 
```
              
Thanks
Sachin v Gaikwad

**Comment by scoopex** [comment] 2021-04-06 16:17
Hi @svgaikwad i added a code section to your issue description to make it readable.
The problem described by your issue not seems to be related to this tool  - therefore i close this issue.

If you are still in the opinion that the problem is originated in this too, just reopen the issue with:
- a complete (and redacted) config
- a description of your environment
- log output
- a redacted example ldap entry which causes the described problem

**Closed as completed by scoopex** 2021-04-06 16:17 UTC
